services:
  c-chain-indexer-db:
    restart: unless-stopped
    profiles: [fsp, ftso, fdc]
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - /data/flare/indexer_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--host", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  c-chain-indexer:
    restart: unless-stopped
    profiles: [fsp, ftso, fdc]
    image: ghcr.io/flare-foundation/flare-system-c-chain-indexer:v1.0.0
    volumes:
      - ./mounts/c-chain-indexer/config.toml:/app/config.toml
    depends_on:
      c-chain-indexer-db:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal:host-gateway

  system-client:
    restart: unless-stopped
    profiles: [fsp, system-client]
    image: ghcr.io/flare-foundation/flare-system-client:v1.0.1
    volumes:
      - ./mounts/system-client/config.toml:/app/config.toml
    ports:
      - "9090:9090"
    environment:
      SYSTEM_CLIENT_SENDER_PRIVATE_KEY: ${SIGNING_PK}
      SIGNING_POLICY_PRIVATE_KEY: ${SIGNING_PK}
      PROTOCOL_MANAGER_SUBMIT_PRIVATE_KEY: ${SUBMIT_PK}
      PROTOCOL_MANAGER_SUBMIT_SIGNATURES_PRIVATE_KEY: ${SIGNATURES_PK}
      PROTOCOL_X_API_KEY_100: ${PROTOCOL_X_API_KEY_100}
      PROTOCOL_X_API_KEY_200: ${PROTOCOL_X_API_KEY_200}
    # NOTE: Voting round 90s + reveal deadline 45s
    stop_grace_period: 135s 
    depends_on:
      - c-chain-indexer
    extra_hosts:
      - host.docker.internal:host-gateway

  ftso-client:
    restart: unless-stopped
    profiles: [fsp, ftso]
    image: ghcr.io/flare-foundation/ftso-scaling:v1.0.2
    env_file:
      - ./mounts/ftso-client/.env
    command: "node dist/apps/ftso-data-provider/apps/ftso-data-provider/src/main.js"
    # NOTE: Voting round 90s + reveal deadline 45s
    stop_grace_period: 135s 
    depends_on:
      - c-chain-indexer

  fdc-client:
    restart: unless-stopped
    profiles: [fsp, fdc]
    image: ghcr.io/flare-foundation/fdc-client:v1.0.1
    volumes:
      - ./mounts/fdc-client/config.toml:/app/configs/userConfig.toml
    depends_on:
      - c-chain-indexer
    # NOTE: Voting round 90s + reveal deadline 45s
    stop_grace_period: 135s 

  fast-updates:
    restart: unless-stopped
    profiles: [fast-updates]
    image: ghcr.io/flare-foundation/fast-updates/go-client:v1.0.0
    volumes:
      - ./mounts/fast-updates/config.toml:/app/config.toml
    environment:
      SIGNING_PRIVATE_KEY: ${SIGNING_PK}
      ACCOUNTS: ${FAST_UPDATES_ACCOUNTS}
      SORTITION_PRIVATE_KEY: ${FAST_UPDATES_SORTITION_PRIVATE_KEY}
    depends_on:
      - c-chain-indexer
    extra_hosts:
      - host.docker.internal:host-gateway

  value-provider:
    profiles: [scaling]
    container_name: ${COMPOSE_PROJECT_NAME}-value-provider
    image: ghcr.io/flare-foundation/ftso-v2-example-value-provider:latest
    #image: a41ventures/ftso-v2-example-value-provider:latest
    ports:
      - "3101:3101"
    environment:
      FEED_CALIBRATION_ENABLED: true
      IDENTITY_ADDRESS: ${IDENTITY}

