# options are: "coston", "songbird", "coston2", "flare"
chain = "${NETWORK}"

protocol_id = 200

[db]
host = "c-chain-indexer-db"
port = 3306
database = "flare_ftso_indexer"
username = "root"
password = "root"
log_queries = false  # Log db queries (for debugging)

[rest_server]
# Addr optionally specifies the FSP client address for the server to listen on, in the form "host:port". If empty, ":http" (port 80) is used. The service names are defined in RFC 6335 and assigned by IANA. See net.Dial for details of the address format.
addr = ":8080"
api_key_name = "X-API-KEY"
api_keys = $FDC_KEYS
title = "FDC protocol data provider API"
fsp_sub_router_title = "FDC protocol data provider for FSP client"
fsp_sub_router_path = "/fsp"
da_sub_router_title = "DA endpoints"
da_sub_router_path = "/da"
version = "0.0.0"
swagger_path = "/api-doc"

[logger]
file = ""
level = "INFO"
console = true
